services:
  backend:
    ports:
    - "5001:5000"
    container_name: realiti
    build:
      context: ./backend
    env_file: ./.env
    volumes:
      - ./backend:/app
  db:
    image: postgres:17
    container_name: realitiDB
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
