"""Added title and user relationship to post

Revision ID: 60b87b00b187
Revises: 6ec113204b1a
Create Date: 2026-04-20 16:20:15.618316

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "60b87b00b187"
down_revision = "6ec113204b1a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("title")

    # ### end Alembic commands ###
