"""added postdislikes table

Revision ID: 638be7be03d9
Revises: f6f28ab4f071
Create Date: 2026-05-28 02:31:40.097359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638be7be03d9'
down_revision = 'f6f28ab4f071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_dislikes',
    sa.Column('postId', sa.Integer(), nullable=False),
    sa.Column('userSentDislike', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['post.id'], ),
    sa.ForeignKeyConstraint(['userSentDislike'], ['user.id'], ),
    sa.PrimaryKeyConstraint('postId', 'userSentDislike')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_dislikes')
    # ### end Alembic commands ###
