"""Added post tags

Revision ID: 879783582bb2
Revises: d1e2f3a4b5c6
Create Date: 2026-09-03 03:32:38.990743

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "879783582bb2"
down_revision = "d1e2f3a4b5c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("experience", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("city", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("state", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("state")
        batch_op.drop_column("city")
        batch_op.drop_column("experience")

    # ### end Alembic commands ###
