"""baseline schema

Revision ID: c855c01a645e
Revises:
Create Date: 2026-07-22 22:52:10.545929

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c855c01a645e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=False),
        sa.Column("last_name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "realtor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("added_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "state", name="uq_realtor_name_state"),
    )
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("s3_url", sa.String(), nullable=True),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.Column("realtor_id", sa.Integer(), nullable=True),
        sa.Column("verification_status", sa.String(), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["realtor_id"],
            ["realtor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "post_dislikes",
        sa.Column("postId", sa.Integer(), nullable=False),
        sa.Column("userSentDislike", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["postId"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userSentDislike"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("postId", "userSentDislike"),
    )
    op.create_table(
        "post_likes",
        sa.Column("postId", sa.Integer(), nullable=False),
        sa.Column("userSentLike", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["postId"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userSentLike"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("postId", "userSentLike"),
    )
    op.create_table(
        "replies",
        sa.Column("postId", sa.Integer(), nullable=False),
        sa.Column("userReplied", sa.Integer(), nullable=False),
        sa.Column("reply_text", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("replied_at", sa.DateTime(), nullable=True),
        sa.Column("parent_reply_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_reply_id"],
            ["replies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["postId"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userReplied"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("reporter_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_url", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("report")
    op.drop_table("replies")
    op.drop_table("post_likes")
    op.drop_table("post_dislikes")
    op.drop_table("post")
    op.drop_table("realtor")
    op.drop_table("user")
    # ### end Alembic commands ###
