"""added postlike table

Revision ID: f6f28ab4f071
Revises: 60b87b00b187
Create Date: 2026-05-15 22:56:30.479529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f28ab4f071'
down_revision = '60b87b00b187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
    sa.Column('postId', sa.Integer(), nullable=False),
    sa.Column('userSentLike', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['post.id'], ),
    sa.ForeignKeyConstraint(['userSentLike'], ['user.id'], ),
    sa.PrimaryKeyConstraint('postId', 'userSentLike')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_likes')
    # ### end Alembic commands ###
